container:
  repository: kandemir08/test-registry
  tag: 1.0.2
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30001

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  startup:
    path: /health
    port: 5000
    periodSeconds: 2
    failureThreshold: 30

  readiness:
    path: /health
    port: 5000
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3

  liveness:
    path: /health
    port: 5000
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3