apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: supportassistant
    namespace: ci00099030-pserver-supportassistant
    releaseName: supportassistant
    additionalValuesFiles:
      - ../values-supportassistant.yaml

helmGlobals:
  chartHome: ../../../charts